local objects = {
    {
      id = 1,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 208,
      y = 240,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 2,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 224,
      y = 240,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 3,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 240,
      y = 240,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 4,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 256,
      y = 240,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 5,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 272,
      y = 240,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 6,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 576,
      y = 160,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 7,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 592,
      y = 160,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 8,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 576,
      y = 240,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 9,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 592,
      y = 240,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 10,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 448,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 11,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 464,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 12,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 480,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 13,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 496,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 14,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 512,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 15,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 528,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 16,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 48,
      y = 16,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 17,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 64,
      y = 16,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 18,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 48,
      y = 32,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 19,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 64,
      y = 32,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 20,
      name = "Gem",
      type = "",
      shape = "rectangle",
      x = 128,
      y = 128,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 54,
      visible = true,
      properties = {}
    },
    {
      id = 21,
      name = "Gem",
      type = "",
      shape = "rectangle",
      x = 416,
      y = 64,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 54,
      visible = true,
      properties = {}
    },
    {
      id = 22,
      name = "Gem",
      type = "",
      shape = "rectangle",
      x = 704,
      y = 112,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 54,
      visible = true,
      properties = {}
    }
  }


return objects