local objects = {
    {
      id = 1,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 208,
      y = 224,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 2,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 272,
      y = 224,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 3,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 64,
      y = 32,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 4,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 144,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 5,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 176,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 6,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 208,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 7,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 240,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 8,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 304,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 9,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 336,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 10,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 368,
      y = 48,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 11,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 432,
      y = 64,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 12,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 464,
      y = 64,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 13,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 512,
      y = 96,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 14,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 544,
      y = 96,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 15,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 576,
      y = 96,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 16,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 608,
      y = 96,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 17,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 640,
      y = 96,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 18,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 672,
      y = 112,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 19,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 688,
      y = 112,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 20,
      name = "Gem",
      type = "",
      shape = "rectangle",
      x = 240,
      y = 208,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 54,
      visible = true,
      properties = {}
    },
    {
      id = 21,
      name = "Gem",
      type = "",
      shape = "rectangle",
      x = 32,
      y = 32,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 54,
      visible = true,
      properties = {}
    },
    {
      id = 22,
      name = "Gem",
      type = "",
      shape = "rectangle",
      x = 768,
      y = 112,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 54,
      visible = true,
      properties = {}
    }
  }


return objects